### ISSUE TITLE
actions fail

### ISSUE THREAD

**Issue by bigmangos** [qianxi0410/gossip#36]
Q1: 4 actions
when I write a issue, it's starting 4 actions.

Q2: action fail

[deploy-to-vercel (ubuntu-latest, 17.x)](https://github.com/bigmangos/gossip/runs/8056703088?check_suite_focus=true#step:7:134)
not supported event_type

[deploy-to-vercel (ubuntu-latest, 17.x)](https://github.com/bigmangos/gossip/runs/8056703088?check_suite_focus=true#step:7:135)
Cannot read properties of undefined (reading 'find')

**Comment by qianxi0410** [comment]
I also got this error, see: https://github.com/amondnet/vercel-action/issues/177

**Comment by qianxi0410** [comment]
In fact, even if an error is reported, the deployment should be successful.

**Comment by qianxi0410** [comment]
@bigmangos 

Clone the project and run the vercel command locally.
Before you run the vervel command locally, please fill in your env file.
I tested it with my bot account and it works.

https://gossip-vercel-test-qianxi0410-bot.vercel.app/

**Comment by bigmangos** [comment]
@qianxi0410 how to fill in env file? login the vercel account?
I will run locally to test. 
tks
